name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 */18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.CONTRIBUTION_3D }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: ${{ github.repository_count }}
      - name: Commit & Push
        run: |
          git config user.name RodrigoAnjos2004
          git config user.email anjosrodrigo2004@gmail.com
          git add -A .
          git commit -m "Personal 3d Contributions images updated"
          git push
